### ISSUE TITLE
Замечания по lw3

### ISSUE THREAD

**Issue by lulldev** [foise/labweb#3]
weekdays является частью таблицы. Абстракция таблицы хорошо подходит и для структурирования заголовка через thead/th.

**Comment by lulldev** [comment]
лучше использовать класс и не стилизовать теги

```css
span {
  color: gray;
}
```
